---
name: "Build and deploy marvinhooks"
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
jobs:
  build:
    runs-on:  uorux-scale-set 
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          - name: Fix cachix installer
        run: sudo apt update && sudo apt install -y lzma xz-utils
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build image
        run: nix build .#docker
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker load < result

          docker tag marvinhooks:latest ghcr.io/${{ github.repository }}/marvinhooks:latest
          docker push ghcr.io/${{ github.repository }}/marvinhooks:latest
